version: '3'

services:
  wechat_ferry:
    image: aimi614/docker_wechat:latest  # 指定镜像名称和标签
    container_name: wechat_ferry  # 指定容器名称
    restart: always  # 设置容器总是重启
    ports:
      - "13389:3389"  # 映射 xRDP 端口
      - "18001:8001"  # 映射 WeChatFerry 命令端口
      - "18002:8002"  # 映射 WeChatFerry 消息端口
    volumes:
      - ./wechat/program:/root/.wine/drive_c/Program Files/Tencent/WeChat  # 挂载微信程序目录
      - ./wechat/share/icons:/root/.local/share/icons  # 挂载图标目录
      - ./wechat/user_dat:/root/.wine/drive_c/users/root/AppData/Roaming/Tencent/WeChat  # 挂载微信用户数据目录
    ulimits:
      nofile:
        soft: 8192  # 设置文件描述符软限制
        hard: 8192  # 设置文件描述符硬限制 